server:
  port: 8888
  
spring:
  datasource:
    url: jdbc:mysql://192.168.7.1:3306/woniuxybook
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.woniuxy.domain     
 